CREATE TABLE bestiaire(
        id MEDIUMINT,
        nom TEXT NOT NULL,
        niveau_min MEDIUMINT,
        niveau_max MEDIUMINT,
        pv_max_min MEDIUMINT,
        pv_max_max MEDIUMINT,
        vue MEDIUMINT,
        regeneration MEDIUMINT,
        degats MEDIUMINT,
        attaque MEDIUMINT,
        defense MEDIUMINT,
        sagesse MEDIUMINT,
        vigueur MEDIUMINT,
        armure_min MEDIUMINT,
        armure_max MEDIUMINT,
        last_update DATE,
        INDEX(nom(10)),
        PRIMARY KEY (id)
) CHARACTER SET utf8;
