CREATE TABLE equipement (
	braldun MEDIUMINT,
	nom_type_buisson TEXT,
	id_equipement TEXT,
	nom TEXT,
	qualite TEXT,
	emplacement TEXT,
	niveau TEXT,
	id_type_equipement TEXT,
	id_type_emplacement TEXT,
	nom_type_emplacement TEXT,
	nom_systeme_type_emplacement TEXT,
       	nb_runes TEXT,
       	armure TEXT,
	`force` TEXT,
	agilite TEXT,
	vigueur TEXT,
	sagesse TEXT,
	vue TEXT,
	attaque TEXT,
	degat TEXT,
	defense TEXT,
	suffixe TEXT,
	poids TEXT,
	etat_courant TEXT,
	etat_initial TEXT,
	ingredient TEXT,
	nom_systeme_type_ingredient TEXT,
	armure_equipement_bonus TEXT,
	vernis_bm_armure_equipement_bonus TEXT,
	agilite_equipement_bonus TEXT,
	vernis_bm_agilite_equipement_bonus TEXT,
       	force_equipement_bonus TEXT,
       	vernis_bm_force_equipement_bonus TEXT,
       	sagesse_equipement_bonus TEXT,
       	vernis_bm_sagesse_equipement_bonus TEXT,
       	vigueur_equipement_bonus TEXT,
       	vernis_bm_vigueur_equipement_bonus TEXT,
       	vernis_bm_vue_equipement_bonus TEXT,
       	vernis_bm_attaque_equipement_bonus TEXT,
       	vernis_bm_degat_equipement_bonus TEXT,
       	vernis_bm_defense_equipement_bonus TEXT,
       	id_rune_equipement_rune1 TEXT,
	nom_type_rune1 TEXT,
       	id_rune_equipement_rune2 TEXT,
	nom_type_rune2 TEXT,
       	id_rune_equipement_rune3 TEXT,
	nom_type_rune3 TEXT,
       	id_rune_equipement_rune4 TEXT,
	nom_type_rune4 TEXT,
       	id_rune_equipement_rune5 TEXT,
	nom_type_rune5 TEXT,
       	id_rune_equipement_rune6 TEXT,
	nom_type_rune6 TEXT,
	INDEX(braldun)
) CHARACTER SET utf8;


CREATE TABLE charrette (
	idBraldun MEDIUMINT,
	objet TEXT,
	contenu TEXT,
	INDEX(idBraldun)
) CHARACTER SET utf8;

CREATE TABLE laban (
	idBraldun MEDIUMINT,
	objet TEXT,
	contenu TEXT,
	INDEX(idBraldun)
) CHARACTER SET utf8;